### ISSUE TITLE
KatakanaSpellCheck don't function

### ISSUE THREAD

**Issue by kongou-ae** [redpen-cc/redpen#513] opened 2015-11-18 16:09 UTC
I tried to use KatakanaSpellCheck. But KatakanaSpellCheck didn't function. It's result is [here](https://gist.github.com/kongou-ae/9baef50bd0e22e905a3b).

Please tell me wtha to do.

**Comment by takahi-i** [comment] 2015-11-20 01:29
I have reproduced the problem in my environment. The reason why KatakanaSpellCheckValiadtor does not work as expected is that I added both "インデクス" and "インデックス" in the skip word list. I will add the parameter to disable to default dictionary for KakatakanSpellCheckValidator. The upcoming fix will enable you to disable the default dictionary as follows.

    <validator name="KatakanaSpellCheck">
       <property name="dict" value="spell.dat"/>
       <property name="default-dict" value ="disable" / >
    </validator>

**Comment by takahi-i** [comment] 2015-11-20 02:15
I have merged the patch to add **disable-default** property in #515. In my environment the patch works.

```
$bin/redpen -c redpen-conf.xml -f markdown sample.md ~/IdeaProjects/redpen/redpen-distribution/target/redpen-distribution-1.4.1/bin/redpen -c redpen-conf.xml -f markdown sample.md
...
[2015-11-20 11:08:37.803][INFO ] cc.redpen.validator.Validator - min_ratio is set to 0.1
[2015-11-20 11:08:37.803][INFO ] cc.redpen.validator.Validator - min_freq is not set. Use default value of 5
[2015-11-20 11:08:37.805][INFO ] cc.redpen.validator.Validator - max_num is set to 1500
[2015-11-20 11:08:37.805][INFO ] cc.redpen.validator.Validator - max_num is not set. Use default value of 5
[2015-11-20 11:08:37.842][INFO ] cc.redpen.validator.JavaScriptValidator - JavaScript validators directory: /Users/takahi-i/IdeaProjects/redpen/redpen-distribution/target/redpen-distribution-1.4.1/js
sample.md:1: ValidationError[ParagraphNumber], The number of paragraphs exceeds the maximum of 8. at line: どうだー
sample.md:7: ValidationError[KatakanaSpellCheck], Found a Katakana word "インデデクス", which is similar to "インデクス" at position 3. at line: インデデクス 
```

I used the following redpen configuration file which tune the min_ratio of KatakanSpellCheck to avoid the wrong misspelled words reported from KatakanaSpellCheck.

```
<redpen-conf lang="ja">
  <validators>
    <validator name="SentenceLength">
      <property name="max_len" value="100"/>
    </validator>
    <validator name="KatakanaEndHyphen"/>
    <validator name="KatakanaSpellCheck">
      <property name="dict" value="spell.dat"/>
      <property name="disable-default" value="true"/>
      <property name="min_ratio" value="0.1"/>
    </validator>
    <validator name="SectionLength">
      <property name="max_num" value="1500"/>
    </validator>
    <validator name="ParagraphNumber"/>
    <validator name="SuccessiveWord" />
    <validator name="JavaScript" />
  </validators>
</redpen-conf> 
```

The patch is going to be bundled in the next minor release 1.4.2. I will close this issue. When you have still have the problem, please let me know. I will create a new issue or reopen this issue.

**Closed** 2015-11-20 02:15 UTC
