### ISSUE TITLE
redpen throws an exception when I use glossary list in asciidoc

### ISSUE THREAD

**Issue by kyonmm** [redpen-cc/redpen#509] opened 2015-11-17 01:47 UTC
when I run this command with asciidoc, then redpen log a exception.

    redpen.bat -f asciidoc -r plain2 -c redpen.config sample.adoc

* Infrastructure
  * redpen version is 6999fbdd
  * OS : Windows 8.1
  * JDK : 1.8.0_51

redpen.config

    <redpen-conf lang="ja">
      <validators>
        <validator name="SentenceLength" />
        <validator name="CommaNumber" />
        <validator name="SuccessiveWord" />
        <validator name="KatakanaSpellCheck"/>
        <validator name="InvalidExpression"/>
        <validator name="JapaneseStyle"/>
        <validator name="DoubleNegative"/>
        <validator name="FrequentSentenceStart"/>
      </validators>
  </redpen-conf>

sample.adoc

    = SampleDoc
    v0.0.2, 2015-11-17
    :last-update-label!:

    == 用語定義
    ユビキタス言語を定義します。

    Some word::
    なにかの意味をのせて用例をのせます。

    リリース::
    ソフトウェアを顧客に提供することです。

    redpen::
    RedPen はオープンソースの校正ツールです。RedPen は技術文書が文書規約に従って書かれているかを自動検査します。	現在の RedPen 日本語ドキュメントは十分検査されておりません。校正にはもう少々時間がかかる予定です。誤りなど見つかりましたら、https://github.com/redpen-cc/redpen-doc-ja に Issue 登録しておしらせ頂けると幸いです。

Log

    d:\apps\redpen\redpen-distribution-1.4.1\bin\redpen.bat -f asciidoc -r plain2 -c redpen.config sample.adoc
    [2015-11-17 10:32:41.979][INFO ] cc.redpen.Main - Configuration file: D:\memo\redpen.config
    [2015-11-17 10:32:41.984][INFO ] cc.redpen.ConfigurationLoader - Loading config from specified config file: "D:\memo\redpen.config"
    [2015-11-17 10:32:41.992][INFO ] cc.redpen.ConfigurationLoader - Succeeded to load configuration file
    [2015-11-17 10:32:41.992][INFO ] cc.redpen.ConfigurationLoader - Language is set to "ja"
    [2015-11-17 10:32:41.992][WARN ] cc.redpen.ConfigurationLoader - No type configuration...
    [2015-11-17 10:32:41.993][INFO ] cc.redpen.ConfigurationLoader - No "symbols" block found in the configuration
    [2015-11-17 10:32:42.027][INFO ] cc.redpen.config.SymbolTable - "ja" is specified.
    [2015-11-17 10:32:42.027][INFO ] cc.redpen.config.SymbolTable - "normal" type is specified
    [2015-11-17 10:32:42.281][INFO ] cc.redpen.parser.SentenceExtractor - "[縲・ ・・ ・‐" are added as a end of sentence characters
    [2015-11-17 10:32:42.281][INFO ] cc.redpen.parser.SentenceExtractor - "[窶・ 窶拆" are added as a right quotation characters
    [2015-11-17 10:32:42.287][INFO ] cc.redpen.validator.Validator - max_len is not set. Use default value of 120
    [2015-11-17 10:32:42.288][INFO ] cc.redpen.validator.Validator - max_num is not set. Use default value of 3
    [2015-11-17 10:32:42.301][INFO ] cc.redpen.util.DictionaryLoader - Succeeded to load katakana word dictionary.
    [2015-11-17 10:32:42.301][INFO ] cc.redpen.validator.Validator - min_ratio is not set. Use default value of 0.30000001192092896
    [2015-11-17 10:32:42.301][INFO ] cc.redpen.validator.Validator - min_freq is not set. Use default value of 5
    [2015-11-17 10:32:42.303][INFO ] cc.redpen.util.DictionaryLoader - Succeeded to load invalid expression.
    [2015-11-17 10:32:42.310][INFO ] cc.redpen.util.DictionaryLoader - Succeeded to load double negative expression rules.
    [2015-11-17 10:32:42.312][INFO ] cc.redpen.util.DictionaryLoader - Succeeded to load double negative words.
    [2015-11-17 10:32:42.315][INFO ] cc.redpen.validator.Validator - leading_word_limit is not set. Use default value of 3
    [2015-11-17 10:32:42.316][INFO ] cc.redpen.validator.Validator - percentage_threshold is not set. Use default value of 25
    [2015-11-17 10:32:42.317][INFO ] cc.redpen.validator.Validator - min_sentence_count is not set. Use default value of 5
    [2015-11-17 10:32:50.487][ERROR] org.asciidoctor.RedPenTreeProcessor - Exception when traversing AsciiDoc blocks
    java.lang.ClassCastException: org.jruby.RubyArray cannot be cast to org.asciidoctor.ast.AbstractBlock
            at org.asciidoctor.RedPenTreeProcessor.traverse(RedPenTreeProcessor.java:185) [redpen-core-1.4.1.jar:na]
            at org.asciidoctor.RedPenTreeProcessor.traverse(RedPenTreeProcessor.java:206) [redpen-core-1.4.1.jar:na]
            at org.asciidoctor.RedPenTreeProcessor.traverse(RedPenTreeProcessor.java:181) [redpen-core-1.4.1.jar:na]
            at org.asciidoctor.RedPenTreeProcessor.process(RedPenTreeProcessor.java:136) [redpen-core-1.4.1.jar:na]
            at org.asciidoctor.extension.Treeprocessor.process(Treeprocessor.java:22) [asciidoctorj-1.5.2.jar:1.5.2]
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
            at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
            at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:455) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:316) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:61) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:127) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.RubyMethod.call(RubyMethod.java:128) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.RubyMethod$INVOKER$i$call.call(RubyMethod$INVOKER$i$call.gen) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrNBlock.call(JavaMethod.java:297) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.AndNode.interpret(AndNode.java:93) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.AndNode.interpret(AndNode.java:93) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.IfNode.interpret(IfNode.java:110) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.Block.yield(Block.java:142) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.RubyArray.eachCommon(RubyArray.java:1606) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.RubyArray.each(RubyArray.java:1613) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.IfNode.interpret(IfNode.java:116) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.BlockNode.interpret(BlockNode.java:71) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.IfNode.interpret(IfNode.java:118) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:139) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.IfNode.interpret(IfNode.java:118) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.BlockNode.interpret(BlockNode.java:71) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.RescueNode.interpret(RescueNode.java:116) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.ReturnNode.interpret(ReturnNode.java:92) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112) [jruby-complete-1.7.16.1.jar:na]
            at org.jruby.gen.InterfaceImpl1324502689.load(org/jruby/gen/InterfaceImpl1324502689.gen:13) [jruby-complete-1.7.16.1.jar:na]
            at org.asciidoctor.internal.JRubyAsciidoctor.readDocumentStructure(JRubyAsciidoctor.java:230) [asciidoctorj-1.5.2.jar:1.5.2]
            at cc.redpen.parser.AsciiDocParser.parse(AsciiDocParser.java:80) [redpen-core-1.4.1.jar:na]
            at cc.redpen.parser.BaseDocumentParser.parse(BaseDocumentParser.java:47) [redpen-core-1.4.1.jar:na]
            at cc.redpen.RedPen.parse(RedPen.java:126) [redpen-core-1.4.1.jar:na]
            at cc.redpen.Main.run(Main.java:169) [redpen-cli-1.4.1.jar:na]
            at cc.redpen.Main.main(Main.java:59) [redpen-cli-1.4.1.jar:na]
    [2015-11-17 10:32:50.491][INFO ] cc.redpen.parser.AsciiDocParser - Asciidoctor parser error: org.asciidoctor.ast.SectionImpl cannot be cast to org.jruby.RubyObject
    Document: sample.adoc

**Comment by takahi-i** [comment] 2015-11-17 01:58
Thank you very much for the valuable report @kyonmm! I have reproduce the problem in my environment. It looks like RedPen parser are not able to handle AsciiDoc **Labeled, multi-line** block, a kind of list form (Ref http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#lists).

**Comment by takahi-i** [comment] 2015-11-17 02:03
We will look into the code and fix the problem.

**Comment by gerryhocks** [comment] 2015-11-17 08:40
Thank you again @kyonmm - I am currently working on improvements to AsciiDoc parsing in RedPen - I will make sure your example is in a test case for the improved parser.

**Comment by takahi-i** [comment] 2015-11-17 08:59
:+1:

**Comment by kyonmm** [comment] 2015-11-18 03:00
Thank you so mush @takahi-i @gerryhocks !
redpen asciidoc parser improvements is good news for me, cause I always write a document with asciidoc.

**Comment by takahi-i** [comment] 2015-12-01 06:25
@kyonmm I merged the changes for brand new AsciiDoc parser #514. Hopefully the parser works for you. I will close this issue. Please let us know when you still have problems. We will  create another issue or reopen this.

**Closed by takahi-i** 2015-12-01 06:25 UTC
