### ISSUE TITLE
Do I remove a js directory?

### ISSUE THREAD

**Issue by karronoli** [redpen-cc/redpen#494] opened 2015-10-07 07:07 UTC
Do I remove a js directory after redpen command is exited?

redpen command create a js directory every time.
https://github.com/redpen-cc/redpen/blob/v1.4.0/redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java#L69

$ ls
$ redpen -v
1.4.0
$ redpen -c /path/to/redpen-conf-en.xml /path/to/test.txt
...some output...
$ ls
js

**Comment by takahi-i** [comment] 2015-10-07 10:43
Thank you a lot for creating the issue @karronoli!  It looks like a bug which create a **js** directory int the current directory. I succeeded to reproduce the issue.

**Comment by yusuke** [comment] 2015-10-13 07:57
Actually this is an expected behavior.
"js" is the directory where you put JavaScript based validators.
And JavaScriptValidator is enabled by default from RedPen v1.4.

But I assume that it's confusing. I'll change the behavior to just put a info level log message that reports the directory is missing.

**Comment by yusuke** [comment] 2015-10-13 08:19
Fixed in PR#499
https://github.com/redpen-cc/redpen/pull/499

**Comment by takahi-i** [comment] 2015-10-14 04:09
Fixed with #499.

**Closed by takahi-i** 2015-10-14 04:09 UTC
