### ISSUE TITLE
JavaScrpit validators are not loaded from REDPEN_HOME\js

### ISSUE THREAD

**Issue by so-c** [redpen-cc/redpen#501] opened 2015-10-18 02:30 UTC
I expect JavaScript validators are loaded REDPEN_HOME\js when configured JavaScriptValidator  without script-path property. Actually they loaded from .\js. if .\js is not exsits, it is created.

I shows my enbironment below.
- RedPen 1.4.0
- Windows 10
- Java 1.8 update 45

I tried write a unit test for JavaScriptValidator.

```Java
    @Test
    public void testLoadJSValidatorFromRedPenHomeJs() throws Exception {
        Path redPenHome = Files.createTempDirectory(null);
        System.setProperty("REDPEN_HOME", redPenHome.toString());
        Path jsDir = Files.createDirectories(Paths.get(System.getProperty("REDPEN_HOME"), "js"));
        Path jsValidator = Files.createFile(Paths.get(jsDir.toString(), "test.js"));
        
        ValidatorConfiguration vc = new ValidatorConfiguration("JavaScriptValidator");
        JavaScriptValidator sut = new JavaScriptValidator();
        sut.preInit(vc, null);

        assertEquals(1, sut.scripts.size());
    }

    @Test
    public void testLoadJSValidatorFromScriptPath() throws Exception {
        Path jsDir = Files.createDirectories(Paths.get(Files.createTempDirectory(null).toString(), "js"));
        Path jsValidator = Files.createFile(Paths.get(jsDir.toString(), "test.js"));
        
        ValidatorConfiguration vc = new ValidatorConfiguration("JavaScriptValidator").addAttribute("script-path", jsDir.toString());
        JavaScriptValidator sut = new JavaScriptValidator();
        sut.preInit(vc, null);

        assertEquals(1, sut.scripts.size());
    }
```

testLoadJSValidatorFromScriptPath success but testLoadJSValidatorFromRedPenHomeJs fails.

```
junit.framework.AssertionFailedError: expected:<1> but was:<0>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at cc.redpen.validator.JavaScriptValidatorTest.testLoadJSValidatorFromRedPenHomeJs(JavaScriptValidatorTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by takahi-i** [comment] 2015-10-18 04:05
Thank you very much for the valuable report @so-c. We will look into the problem.

**Comment by takahi-i** [comment] 2015-10-30 01:37
#503 (merged) would fix the problem. Please let me know when you still have the problem. I will reopen this issue when the problem is not fixed in your environment.

**Closed by takahi-i** 2015-10-30 01:37 UTC
